const REVALIDATE_SECONDS = parseInt(process.env.NEXT_PUBLIC_REVALIDATE, 10)
const GITHUB_SECRET = process.env.NEXT_PUBLIC_GITHUB_SECRET
const GITHUB_HEADER_NAME = 'x-hub-signature-256'
const GITHUB_HASH_ALG = 'sha256'
export {
  REVALIDATE_SECONDS,
  GITHUB_SECRET,
  GITHUB_HEADER_NAME,
  GITHUB_HASH_ALG
}
